org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.213
neo_version_range=[21.1.213,)
loader_version_range=[1,)
registrate_version = MC1.21-1.3.0+67
flywheel_version = 1.0.6

jei_minecraft_version = 1.21.1
jei_version = 19.27.0.340

create_version = 6.0.9-215
ponder_version = 1.0.81
curios_minecraft_version = 1.21.1
curios_version = 9.2.2

# Dev
farmers_delight_version=1.21.1-1.2.8
my_nethers_delight_version=1.8
create_aquatic_ambitions_version=1.21.1-2.0.1
create_dragons_plus_version=1.6.1

## Mod Properties
mod_id=garnished
mod_name=Create: Garnished
mod_license=MIT
mod_version=2.1.9.3
mod_group_id=net.dakotapride.garnished
mod_authors=DakotaPride
mod_description=Cashews! Almonds! Walnuts...