package net.dakotapride.garnished.config;

import net.createmod.catnip.config.ConfigBase;

public class ClientConfig extends ConfigBase {

    public final ConfigGroup client = group(0, "client");

    public ConfigBool voltaicSeaGrassParticles = b(true, "voltaicSeaGrassParticles", Comments.voltaicSeaGrassParticles);
    public ConfigBool abyssalStoneParticles = b(true, "abyssalStoneParticles", Comments.abyssalStoneParticles);
    public ConfigBool wyvernStoneParticles = b(true, "wyvernStoneParticles", Comments.wyvernStoneParticles);

    @Override
    public String getName() {
        return "client";
    }

    private static class Comments {
        static String voltaicSeaGrassParticles = "Controls whether or not particles are generated by voltaic sea grass.";
        static String abyssalStoneParticles = "Controls whether or not particles are generated by abyssal stone.";
        static String wyvernStoneParticles = "Controls whether or not particles are generated by wyvern stone.";
    }
}