package net.dakotapride.creategarnished.config;

import net.createmod.catnip.config.ConfigBase;

public class BlockConfig extends ConfigBase {
    public ConfigBool elvenSweetBerryBushParticles = b(true, "elvenSweetBerryBushParticles", Comments.elvenSweetBerryBushParticles);

    @Override
    public String getName() {
        return "block";
    }

    private static class Comments {
        static String elvenSweetBerryBushParticles = "Controls whether or not particles are generated by Elven Sweet Berry Bushes.";
    }
}
