package net.dakotapride.creategarnished.config;

import net.createmod.catnip.config.ConfigBase;

public class BlockConfig extends ConfigBase {
    public ConfigBool elvenSweetBerryBushParticles = b(true, "elvenSweetBerryBushParticles", Comments.elvenSweetBerryBushParticles);
    public ConfigBool allowForRenewableBirchSap = b(true, "allowForRenewableBirchSap", Comments.allowForRenewableBirchSap);

    @Override
    public String getName() {
        return "block";
    }

    private static class Comments {
        static String elvenSweetBerryBushParticles = "Controls whether or not particles are generated by Elven Sweet Berry Bushes.";
        static String allowForRenewableBirchSap = "Controls whether or not Birch Sap can be generated over time from a Sappy Birch Log.";
    }
}
